import math
import numpy as np
import matplotlib.pyplot as plt
i20=np.genfromtxt('int_n20.dat',usecols=[0,1,2,3],dtype=[('f4'),('f4'),('f4'),('f4')],names=['x','y','e','o'])
d20=np.genfromtxt('der_n20.dat',usecols=[0,1,2,3],dtype=[('f4'),('f4'),('f4'),('f4')],names=['x','y','e','o'])
i40=np.genfromtxt('int_n40.dat',usecols=[0,1,2,3],dtype=[('f4'),('f4'),('f4'),('f4')],names=['x','y','e','o'])
d40=np.genfromtxt('der_n40.dat',usecols=[0,1,2,3],dtype=[('f4'),('f4'),('f4'),('f4')],names=['x','y','e','o'])
i80=np.genfromtxt('int_n80.dat',usecols=[0,1,2,3],dtype=[('f4'),('f4'),('f4'),('f4')],names=['x','y','e','o'])
d80=np.genfromtxt('der_n80.dat',usecols=[0,1,2,3],dtype=[('f4'),('f4'),('f4'),('f4')],names=['x','y','e','o'])
x=np.arange(100)/100.
f=x-0.5*x*x+4.0/3.0*x**3.-x**4./4.0
plt.plot(x,f,color='black')
plt.scatter(i20['x'],i20['y'],marker='D',facecolor='none',edgecolor='red')
plt.scatter(i40['x'],i40['y'],marker='D',facecolor='none',edgecolor='blue')
plt.scatter(i80['x'],i80['y'],marker='D',facecolor='none',edgecolor='green')
plt.xlim(0.0,1.0)
plt.ylim(0.0,1.7)
plt.xlabel('x')
plt.ylabel('$\int{f(x)}$d$x$')
plt.title('$f(x)=1-x+4x^{2}-x^{3}$')
plt.savefig('integ.ps')
plt.clf()
plt.plot([-3e-3,3e-3],[-3e-3,3e-3],color='black')
plt.scatter(i20['e'],i20['o'],marker='D',facecolor='none',edgecolor='red')
plt.scatter(i40['e'],i40['o'],marker='D',facecolor='none',edgecolor='blue')
plt.scatter(i80['e'],i80['o'],marker='D',facecolor='none',edgecolor='green')
plt.xlabel('E')
plt.ylabel('O($\Delta x$)')
plt.xlim(-3e-3,3e-3)
plt.ylim(-3e-3,3e-3)
plt.title('$f(x)=1-x+4x^{2}-x^{3}$')
plt.savefig('ierr.ps')
plt.clf()
f=-1.0+8*x-3*x*x
plt.plot(x,f,color='black')
plt.scatter(d20['x'],d20['y'],marker='D',facecolor='none',edgecolor='red')
plt.scatter(d40['x'],d40['y'],marker='D',facecolor='none',edgecolor='blue')
plt.scatter(d80['x'],d80['y'],marker='D',facecolor='none',edgecolor='green')
plt.xlim(0.0,1.0)
plt.ylim(0.0,4.0)
plt.xlabel('x')
plt.ylabel('d$f(x)$/d$x$')
plt.title('$f(x)=1-x+4x^{2}-x^{3}$')
plt.savefig('deriv.ps')
plt.clf()
plt.plot([0,0.2],[0,0.2],color='black')
plt.scatter(d20['e'],d20['o'],marker='D',facecolor='none',edgecolor='red')
plt.scatter(d40['e'],d40['o'],marker='D',facecolor='none',edgecolor='blue')
plt.scatter(d80['e'],d80['o'],marker='D',facecolor='none',edgecolor='green')
plt.xlabel('E')
plt.ylabel('O($\Delta x$)')
plt.xlim(0,0.2)
plt.ylim(0,0.2)
plt.title('$f(x)=1-x+4x^{2}-x^{3}$')
plt.savefig('derr.ps')
plt.clf()
