CC = clang
CFLAGS = -Wall
all: ex1 ex3 ex6 ex7 ex8 ex9 ex10 ex11 ex12 ex13 ex14 ex15
ex1:
	$(CC) $(CFLAGS) ex1.c -o ex1.o
ex3:
	$(CC) $(CFLAGS) ex3.c -o ex3.o
ex6:
	$(CC) $(CFLAGS) ex6.c -o ex6.o
ex7:
	$(CC) $(CFLAGS) ex7.c -o ex7.o
ex8:
	$(CC) $(CFLAGS) ex8.c -o ex8.o
ex9:
	$(CC) $(CFLAGS) ex9.c -o ex9.o
ex10:
	$(CC) $(CFLAGS) ex10.c -o ex10.o
ex11:
	$(CC) $(CFLAGS) ex11.c -o ex11.o
ex12:
	$(CC) $(CFLAGS) ex12.c -o ex12.o
ex13:
	$(CC) $(CFLAGS) ex13.c -o ex13.o
ex14:
	$(CC) $(CFLAGS) ex14.c -o ex14.o
ex14xtra:
	$(CC) $(CFLAGS) ex14xtra.c -o ex14.o
ex15:
	$(CC) $(CFLAGS) ex15.c -o ex15.o
ex16:
	$(CC) $(CFLAGS) ex16.c -o ex16.o
clean:
	rm -f *.o
